---
- name: Require password for single user mode
  lineinfile:
    state: present
    backup: yes
    dest: /etc/inittab
    line: '~:S:wait:/sbin/sulogin'
  tags: [ 'xen' , 'single_user_mode' ]

# Check for the presence of a bootloader password.
# If one is not found, add it to extlinux.conf
- name: Check for password in extlinux.conf
  command: grep passwd /boot/extlinux.conf
  register: extlinux_password_check
  changed_when: false
  failed_when: extlinux_password_check.stderr
  tags: [ 'xen' , 'bootloader_password' ]

- name: Set bootloader password
  lineinfile:
    state: present
    backup: yes
    dest: /boot/extlinux.conf
    regexp: 'passwd'
    line: 'menu master passwd {{ xen_bootloader_password }}'
    insertafter: '^timeout'
  when: extlinux_password_check.rc != 0 or xen_change_extlinux_password
  tags: [ 'xen' , 'bootloader_password' ]


- name: Set ownership and permissions on /boot/extlinux.conf
  file:
    path: /boot/extlinux.conf
    owner: root
    group: root
    mode: 0600
  tags: xen

- name: Store passwords in /etc/shadow
  lineinfile:
    state: present
    backup: yes
    dest: /etc/pam.d/system-auth
    regexp: 'password.*sufficient'
    line: 'password    sufficient    pam_unix.so try_first_pass use_authtok nullok sha512 shadow'
  tags: xen

- name: Configure kernel network parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
    ignoreerrors: yes
  with_items: xen_kernel_settings

- name: Improve SSL configuration
  lineinfile:
    state: present
    backup: yes
    dest: /etc/init.d/xapissl
    regexp: '^ciphers'
    line: 'ciphers = !SSLv2:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:RSA+AES256-SHA:RSA+AES128-SHA:!aNULL:!MD5:!DSS:!RC4'
  notify: restart xapi
  tags: ssl