---
- name: restart iptables
  service: name=iptables state=restarted

- name: restart ssh
  service: name=sshd state=restarted

- name: restart ntp
  service: name=ntpd state=restarted

- name: run pwconv
  command: /usr/sbin/pwconv