---
- name: restart iptables
  service: name=iptables state=restarted

- name: restart ssh
  service: name=sshd state=restarted

- name: restart ntp
  service: name=ntpd state=restarted

- name: run pwconv
  command: /usr/sbin/pwconv

- name: restart xapi
  command: /opt/xensource/bin/xe-toolstack-restart
  environment:
    PATH: "/opt/xensource/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"